### ISSUE TITLE
Wait!? how did it approved???

### ISSUE THREAD

**Issue by OguzhanUmutlu** [ErikPDev/AutoCropBreak#2]
You just put random
$this->getLogger()->debug("Top found!".(string)$c);
lines??? remove them

**Comment by ErikPDev** [comment]
Those are debug lines which are allowed.

**Comment by ErikPDev** [comment]
And this plugin was approved following the PQRS rules
https://poggit.pmmp.io/rules.edit

**Comment by ErikPDev** [comment]
Deleting this issue since it has nothing to do with the plugin as it's a useless issue.
