### ISSUE TITLE
Sugarcane Dupe

### ISSUE THREAD

**Issue by HazelYT** [ErikPDev/AutoCropBreak#3]
When you place water on top of the sugarcane and take the water back it drops multiple sugarcanes without a cooldown.

**Comment by ErikPDev** [comment]
This is interesting. I'll check it out.

**Comment by ErikPDev** [comment]
PMMP takes the Water block as a new state. I'll upload a fix once I get home.

**Comment by HazelYT** [comment]
> PMMP takes the Water block as a new state. I'll upload a fix once I get home.

Ok, thats great.

**Comment by ErikPDev** [comment]
Fixed on latest phar build
